// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjBancoAPI.Persistence;

#nullable disable

namespace ProjBancoAPI.Migrations
{
    [DbContext(typeof(BancoContext))]
    [Migration("20220221205855_TabelasMapeadas")]
    partial class TabelasMapeadas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProjBancoAPI.Models.Cartao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ExtratoId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExtratoId");

                    b.ToTable("Tbl_Cartao");
                });

            modelBuilder.Entity("ProjBancoAPI.Models.Extrato", b =>
                {
                    b.Property<int>("ExtratoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExtratoId"), 1L, 1);

                    b.Property<decimal>("SaldoAtual")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ExtratoId");

                    b.ToTable("Tbl_Extrato");
                });

            modelBuilder.Entity("ProjBancoAPI.Models.Lancamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Data")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExtratoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ExtratoId");

                    b.ToTable("Tbl_Lancamento");
                });

            modelBuilder.Entity("ProjBancoAPI.Models.Cartao", b =>
                {
                    b.HasOne("ProjBancoAPI.Models.Extrato", "Extrato")
                        .WithMany()
                        .HasForeignKey("ExtratoId");

                    b.Navigation("Extrato");
                });

            modelBuilder.Entity("ProjBancoAPI.Models.Lancamento", b =>
                {
                    b.HasOne("ProjBancoAPI.Models.Extrato", null)
                        .WithMany("Lancamentos")
                        .HasForeignKey("ExtratoId");
                });

            modelBuilder.Entity("ProjBancoAPI.Models.Extrato", b =>
                {
                    b.Navigation("Lancamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
